import {
  OnboardingApplication,
  Account,
  RefreshSchedule,
  IDExpiration,
} from "@/types";

export const mockApplications: OnboardingApplication[] = [
  {
    id: "APP-001",
    status: "submitted",
    submittedAt: "2026-05-15T10:30:00Z",
    updatedAt: "2026-05-15T10:30:00Z",
    businessInfo: {
      legalName: "Evergreen Capital Partners LLC",
      dba: "Evergreen Capital",
      ein: "82-1234567",
      entityType: "LLC",
      stateOfIncorporation: "Delaware",
      dateOfIncorporation: "2019-03-15",
      address: {
        street: "400 Park Avenue, Suite 1200",
        city: "New York",
        state: "NY",
        zip: "10022",
        country: "US",
      },
      phone: "(212) 555-0134",
      website: "https://evergreencapital.com",
      industry: "Investment Management",
      description:
        "Private equity fund focused on mid-market growth companies in technology and healthcare.",
    },
    controlPersons: [
      {
        id: "AP-001",
        firstName: "James",
        lastName: "Mitchell",
        email: "j.mitchell@evergreencapital.com",
        title: "Managing Partner",
        phone: "(212) 555-0135",
        dateOfBirth: "1975-08-22",
        ssn: "***-**-4521",
        address: {
          street: "88 Central Park West, Apt 14B",
          city: "New York",
          state: "NY",
          zip: "10023",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***4521",
        idExpiration: "2027-08-22",
      },
    ],
    ubos: [
      {
        id: "UBO-001",
        firstName: "James",
        lastName: "Mitchell",
        email: "j.mitchell@evergreencapital.com",
        ownershipPercentage: 45,
        dateOfBirth: "1975-08-22",
        ssn: "***-**-4521",
        address: {
          street: "88 Central Park West, Apt 14B",
          city: "New York",
          state: "NY",
          zip: "10023",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***4521",
        idExpiration: "2027-08-22",
      },
      {
        id: "UBO-002",
        firstName: "Sarah",
        lastName: "Chen",
        email: "s.chen@evergreencapital.com",
        ownershipPercentage: 35,
        dateOfBirth: "1980-11-05",
        ssn: "***-**-7832",
        address: {
          street: "220 E 72nd St, Apt 8A",
          city: "New York",
          state: "NY",
          zip: "10021",
          country: "US",
        },
        idType: "Passport",
        idNumber: "***7832",
        idExpiration: "2028-03-15",
      },
    ],
    documents: [
      {
        id: "DOC-001",
        name: "Certificate of Formation.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-15T10:25:00Z",
        url: "#",
      },
      {
        id: "DOC-002",
        name: "Operating Agreement.pdf",
        type: "operating_agreement",
        uploadedAt: "2026-05-15T10:26:00Z",
        url: "#",
      },
    ],
    riskScore: 32,
    riskLevel: "low",
    alloyJourneyId: "JRN-EG-001",
    alloyTags: ["us_entity", "registered_investment_advisor", "low_risk"],
    eddRequired: false,
  },
  {
    id: "APP-002",
    status: "edd_required",
    submittedAt: "2026-05-10T14:00:00Z",
    updatedAt: "2026-05-14T09:00:00Z",
    businessInfo: {
      legalName: "Meridian Global Ventures Ltd",
      dba: "Meridian Ventures",
      ein: "98-7654321",
      entityType: "Ltd",
      stateOfIncorporation: "Cayman Islands",
      dateOfIncorporation: "2021-07-01",
      address: {
        street: "PO Box 309, Ugland House",
        city: "George Town",
        state: "Grand Cayman",
        zip: "KY1-1104",
        country: "KY",
      },
      phone: "+1-345-555-0199",
      website: "https://meridianglobal.com",
      industry: "Venture Capital",
      description:
        "Offshore venture capital fund investing in emerging market fintech companies.",
    },
    controlPersons: [
      {
        id: "AP-002",
        firstName: "Ricardo",
        lastName: "Alvarez",
        email: "r.alvarez@meridianglobal.com",
        title: "Director",
        phone: "+1-345-555-0200",
        dateOfBirth: "1982-04-12",
        ssn: "N/A",
        address: {
          street: "14 Seven Mile Beach Rd",
          city: "George Town",
          state: "Grand Cayman",
          zip: "KY1-1205",
          country: "KY",
        },
        idType: "Passport",
        idNumber: "***3847",
        idExpiration: "2027-01-30",
      },
    ],
    ubos: [
      {
        id: "UBO-003",
        firstName: "Ricardo",
        lastName: "Alvarez",
        email: "r.alvarez@meridianglobal.com",
        ownershipPercentage: 60,
        dateOfBirth: "1982-04-12",
        ssn: "N/A",
        address: {
          street: "14 Seven Mile Beach Rd",
          city: "George Town",
          state: "Grand Cayman",
          zip: "KY1-1205",
          country: "KY",
        },
        idType: "Passport",
        idNumber: "***3847",
        idExpiration: "2027-01-30",
      },
    ],
    documents: [
      {
        id: "DOC-003",
        name: "Certificate of Incorporation.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-10T13:55:00Z",
        url: "#",
      },
    ],
    riskScore: 78,
    riskLevel: "high",
    alloyJourneyId: "JRN-MG-001",
    alloyTags: [
      "offshore_entity",
      "high_risk_jurisdiction",
      "edd_required",
    ],
    eddRequired: true,
    eddDocuments: [
      {
        id: "EDD-001",
        label: "Source of Funds Documentation",
        required: true,
        description:
          "Provide documentation showing the source of funds for the entity.",
      },
      {
        id: "EDD-002",
        label: "Audited Financial Statements",
        required: true,
        description:
          "Provide the most recent audited financial statements.",
      },
      {
        id: "EDD-003",
        label: "Explanation of Business Structure",
        required: false,
        description:
          "Provide a written explanation of the entity's corporate structure and rationale for offshore domicile.",
        textResponse:
          "Meridian Global Ventures Ltd was established in the Cayman Islands to facilitate investment from international LPs across multiple jurisdictions...",
      },
    ],
  },
  {
    id: "APP-003",
    status: "approved",
    submittedAt: "2026-04-20T09:00:00Z",
    updatedAt: "2026-04-28T16:00:00Z",
    businessInfo: {
      legalName: "Pinnacle Wealth Advisors Inc",
      dba: "Pinnacle Wealth",
      ein: "45-9876543",
      entityType: "Corporation",
      stateOfIncorporation: "California",
      dateOfIncorporation: "2017-01-10",
      address: {
        street: "1 Market Street, Suite 3600",
        city: "San Francisco",
        state: "CA",
        zip: "94105",
        country: "US",
      },
      phone: "(415) 555-0178",
      website: "https://pinnaclewealth.com",
      industry: "Wealth Management",
      description:
        "Full-service wealth management firm serving high-net-worth individuals and family offices.",
    },
    controlPersons: [
      {
        id: "AP-003",
        firstName: "Diana",
        lastName: "Park",
        email: "d.park@pinnaclewealth.com",
        title: "CEO",
        phone: "(415) 555-0179",
        dateOfBirth: "1970-06-18",
        ssn: "***-**-9012",
        address: {
          street: "450 Pacific Heights Blvd",
          city: "San Francisco",
          state: "CA",
          zip: "94115",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***9012",
        idExpiration: "2026-06-18",
      },
    ],
    ubos: [
      {
        id: "UBO-004",
        firstName: "Diana",
        lastName: "Park",
        email: "d.park@pinnaclewealth.com",
        ownershipPercentage: 55,
        dateOfBirth: "1970-06-18",
        ssn: "***-**-9012",
        address: {
          street: "450 Pacific Heights Blvd",
          city: "San Francisco",
          state: "CA",
          zip: "94115",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***9012",
        idExpiration: "2026-06-18",
      },
    ],
    documents: [
      {
        id: "DOC-004",
        name: "Articles of Incorporation.pdf",
        type: "formation_document",
        uploadedAt: "2026-04-20T08:55:00Z",
        url: "#",
      },
      {
        id: "DOC-005",
        name: "Board Resolution.pdf",
        type: "board_resolution",
        uploadedAt: "2026-04-20T08:56:00Z",
        url: "#",
      },
    ],
    riskScore: 18,
    riskLevel: "low",
    alloyJourneyId: "JRN-PW-001",
    alloyTags: ["us_entity", "wealth_management", "low_risk"],
    eddRequired: false,
  },
  {
    id: "APP-004",
    status: "under_review",
    submittedAt: "2026-05-12T11:00:00Z",
    updatedAt: "2026-05-16T08:00:00Z",
    businessInfo: {
      legalName: "Atlas Infrastructure Fund GP LLC",
      dba: "Atlas Infrastructure",
      ein: "73-1112233",
      entityType: "LLC",
      stateOfIncorporation: "Delaware",
      dateOfIncorporation: "2022-09-01",
      address: {
        street: "200 Clarendon Street, 52nd Floor",
        city: "Boston",
        state: "MA",
        zip: "02116",
        country: "US",
      },
      phone: "(617) 555-0145",
      website: "https://atlasinfra.com",
      industry: "Infrastructure Investment",
      description:
        "Infrastructure-focused private equity GP targeting renewable energy and transportation assets.",
    },
    controlPersons: [
      {
        id: "AP-004",
        firstName: "Michael",
        lastName: "Torres",
        email: "m.torres@atlasinfra.com",
        title: "General Partner",
        phone: "(617) 555-0146",
        dateOfBirth: "1978-12-03",
        ssn: "***-**-5567",
        address: {
          street: "15 Beacon Hill Place",
          city: "Boston",
          state: "MA",
          zip: "02108",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***5567",
        idExpiration: "2028-12-03",
      },
    ],
    ubos: [
      {
        id: "UBO-005",
        firstName: "Michael",
        lastName: "Torres",
        email: "m.torres@atlasinfra.com",
        ownershipPercentage: 40,
        dateOfBirth: "1978-12-03",
        ssn: "***-**-5567",
        address: {
          street: "15 Beacon Hill Place",
          city: "Boston",
          state: "MA",
          zip: "02108",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***5567",
        idExpiration: "2028-12-03",
      },
      {
        id: "UBO-006",
        firstName: "Elena",
        lastName: "Vasquez",
        email: "e.vasquez@atlasinfra.com",
        ownershipPercentage: 30,
        dateOfBirth: "1985-07-20",
        ssn: "***-**-8890",
        address: {
          street: "42 Commonwealth Ave",
          city: "Boston",
          state: "MA",
          zip: "02116",
          country: "US",
        },
        idType: "Passport",
        idNumber: "***8890",
        idExpiration: "2029-07-20",
      },
    ],
    documents: [
      {
        id: "DOC-006",
        name: "Certificate of Formation.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-12T10:55:00Z",
        url: "#",
      },
    ],
    riskScore: 45,
    riskLevel: "medium",
    alloyJourneyId: "JRN-AI-001",
    alloyTags: ["us_entity", "infrastructure", "medium_risk"],
    eddRequired: false,
  },
  {
    id: "APP-005",
    status: "edd_required",
    submittedAt: "2026-05-08T10:00:00Z",
    updatedAt: "2026-05-16T09:00:00Z",
    businessInfo: {
      legalName: "Cascade Bridge Holdings Ltd",
      dba: "Cascade Bridge",
      ein: "N/A",
      entityType: "Ltd",
      stateOfIncorporation: "British Virgin Islands",
      dateOfIncorporation: "2020-02-14",
      address: {
        street: "Trident Chambers, P.O. Box 146",
        city: "Road Town",
        state: "Tortola",
        zip: "VG1110",
        country: "VG",
      },
      phone: "+1-284-555-0182",
      website: "https://cascadebridge.com",
      industry: "Holding Company",
      description:
        "Multi-jurisdictional holding company structuring private investment vehicles.",
    },
    controlPersons: [
      {
        id: "AP-005",
        firstName: "Henrik",
        lastName: "Lindqvist",
        email: "h.lindqvist@cascadebridge.com",
        title: "Director",
        phone: "+1-284-555-0183",
        dateOfBirth: "1972-11-19",
        ssn: "N/A",
        address: {
          street: "12 Wickhams Cay",
          city: "Road Town",
          state: "Tortola",
          zip: "VG1110",
          country: "VG",
        },
        idType: "Passport",
        idNumber: "***1184",
        idExpiration: "2028-04-10",
      },
    ],
    ubos: [
      {
        id: "UBO-007",
        firstName: "Henrik",
        lastName: "Lindqvist",
        email: "h.lindqvist@cascadebridge.com",
        ownershipPercentage: 70,
        dateOfBirth: "1972-11-19",
        ssn: "N/A",
        address: {
          street: "12 Wickhams Cay",
          city: "Road Town",
          state: "Tortola",
          zip: "VG1110",
          country: "VG",
        },
        idType: "Passport",
        idNumber: "***1184",
        idExpiration: "2028-04-10",
      },
    ],
    documents: [
      {
        id: "DOC-007",
        name: "Certificate of Incorporation.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-08T09:55:00Z",
        url: "#",
      },
    ],
    riskScore: 82,
    riskLevel: "high",
    alloyJourneyId: "JRN-CB-001",
    alloyTags: ["offshore_entity", "bvi", "edd_required"],
    eddRequired: true,
    eddDocuments: [
      {
        id: "EDD-005-1",
        label: "AML Program Information",
        required: true,
        description:
          "Provide a copy of the entity's AML program, policies, and procedures.",
      },
      {
        id: "EDD-005-2",
        label: "Corporate Governance Documents",
        required: true,
        description:
          "Provide bylaws, shareholder agreements, and governance documentation.",
      },
      {
        id: "EDD-005-3",
        label: "Organizational Chart",
        required: true,
        description:
          "Provide a chart depicting parent, subsidiaries, and ownership flow.",
        uploadedFile: {
          id: "DOC-EDD-005-3",
          name: "CascadeBridge_OrgChart.pdf",
          type: "edd_response",
          uploadedAt: "2026-05-13T10:00:00Z",
          url: "#",
        },
        submittedAt: "2026-05-13T10:00:00Z",
      },
      {
        id: "EDD-005-4",
        label: "Audited Financial Statements",
        required: true,
        description: "Provide the most recent audited financial statements.",
      },
    ],
  },
  {
    id: "APP-006",
    status: "edd_required",
    submittedAt: "2026-05-09T13:00:00Z",
    updatedAt: "2026-05-17T11:00:00Z",
    businessInfo: {
      legalName: "Helix Quantitative Strategies LP",
      dba: "Helix Quant",
      ein: "85-2233445",
      entityType: "LP",
      stateOfIncorporation: "Delaware",
      dateOfIncorporation: "2019-09-30",
      address: {
        street: "350 Park Avenue, 14th Floor",
        city: "New York",
        state: "NY",
        zip: "10022",
        country: "US",
      },
      phone: "(212) 555-0211",
      website: "https://helixquant.com",
      industry: "Algorithmic Trading",
      description:
        "Quantitative hedge fund deploying systematic, high-frequency trading strategies.",
    },
    controlPersons: [
      {
        id: "AP-006",
        firstName: "Priya",
        lastName: "Raghavan",
        email: "p.raghavan@helixquant.com",
        title: "General Partner",
        phone: "(212) 555-0212",
        dateOfBirth: "1979-03-22",
        ssn: "***-**-3344",
        address: {
          street: "55 Hudson Yards",
          city: "New York",
          state: "NY",
          zip: "10001",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***3344",
        idExpiration: "2028-03-22",
      },
    ],
    ubos: [
      {
        id: "UBO-008",
        firstName: "Priya",
        lastName: "Raghavan",
        email: "p.raghavan@helixquant.com",
        ownershipPercentage: 50,
        dateOfBirth: "1979-03-22",
        ssn: "***-**-3344",
        address: {
          street: "55 Hudson Yards",
          city: "New York",
          state: "NY",
          zip: "10001",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***3344",
        idExpiration: "2028-03-22",
      },
    ],
    documents: [
      {
        id: "DOC-008",
        name: "Limited Partnership Agreement.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-09T12:55:00Z",
        url: "#",
      },
    ],
    riskScore: 71,
    riskLevel: "high",
    alloyJourneyId: "JRN-HX-001",
    alloyTags: ["us_entity", "high_velocity_trading", "edd_required"],
    eddRequired: true,
    eddDocuments: [
      {
        id: "EDD-006-1",
        label: "≥10% UBO Identification",
        required: true,
        description:
          "Identification documentation for all UBOs owning 10% or more.",
      },
      {
        id: "EDD-006-2",
        label: "Additional Narrative on Account Purpose",
        required: true,
        description:
          "Provide additional detail explaining the intended use of the account.",
        textResponse:
          "Helix will use the Interro account exclusively for LP capital calls and operational disbursements. Trading capital flows through prime brokerage and does not touch this account.",
        submittedAt: "2026-05-14T11:30:00Z",
      },
      {
        id: "EDD-006-3",
        label: "Regulatory Registrations",
        required: true,
        description:
          "Provide proof of regulatory registrations (SEC, CFTC, NFA).",
        uploadedFile: {
          id: "DOC-EDD-006-3",
          name: "Helix_SEC_FormADV.pdf",
          type: "edd_response",
          uploadedAt: "2026-05-14T11:35:00Z",
          url: "#",
        },
        submittedAt: "2026-05-14T11:35:00Z",
      },
    ],
  },
  {
    id: "APP-007",
    status: "edd_required",
    submittedAt: "2026-05-01T14:00:00Z",
    updatedAt: "2026-05-15T16:00:00Z",
    businessInfo: {
      legalName: "Northern Star Family Trust",
      dba: "Northern Star Trust",
      ein: "47-5566778",
      entityType: "Trust",
      stateOfIncorporation: "Wyoming",
      dateOfIncorporation: "2015-06-12",
      address: {
        street: "1700 Lincoln Street",
        city: "Cheyenne",
        state: "WY",
        zip: "82001",
        country: "US",
      },
      phone: "(307) 555-0190",
      website: "",
      industry: "Family Office / Trust",
      description:
        "Multi-generational family trust managing diversified investment portfolio.",
    },
    controlPersons: [
      {
        id: "AP-007",
        firstName: "Margaret",
        lastName: "Holloway",
        email: "m.holloway@northernstartrust.com",
        title: "Trustee",
        phone: "(307) 555-0191",
        dateOfBirth: "1958-09-04",
        ssn: "***-**-7788",
        address: {
          street: "300 W 17th St",
          city: "Cheyenne",
          state: "WY",
          zip: "82001",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***7788",
        idExpiration: "2027-09-04",
      },
    ],
    ubos: [
      {
        id: "UBO-009",
        firstName: "Margaret",
        lastName: "Holloway",
        email: "m.holloway@northernstartrust.com",
        ownershipPercentage: 100,
        dateOfBirth: "1958-09-04",
        ssn: "***-**-7788",
        address: {
          street: "300 W 17th St",
          city: "Cheyenne",
          state: "WY",
          zip: "82001",
          country: "US",
        },
        idType: "Drivers License",
        idNumber: "***7788",
        idExpiration: "2027-09-04",
      },
    ],
    documents: [
      {
        id: "DOC-009",
        name: "Trust Agreement.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-01T13:55:00Z",
        url: "#",
      },
    ],
    riskScore: 64,
    riskLevel: "high",
    alloyJourneyId: "JRN-NS-001",
    alloyTags: ["us_entity", "trust", "edd_required"],
    eddRequired: true,
    eddDocuments: [
      {
        id: "EDD-007-1",
        label: "Corporate Governance Documents",
        required: true,
        description:
          "Provide trust agreement, schedule of trustees and beneficiaries.",
        uploadedFile: {
          id: "DOC-EDD-007-1",
          name: "NorthernStar_TrustAgreement.pdf",
          type: "edd_response",
          uploadedAt: "2026-05-12T09:00:00Z",
          url: "#",
        },
        submittedAt: "2026-05-12T09:00:00Z",
      },
      {
        id: "EDD-007-2",
        label: "Organizational Chart",
        required: true,
        description: "Provide a chart showing trustees, beneficiaries, and grantor relationships.",
        uploadedFile: {
          id: "DOC-EDD-007-2",
          name: "NorthernStar_StructureChart.pdf",
          type: "edd_response",
          uploadedAt: "2026-05-12T09:05:00Z",
          url: "#",
        },
        submittedAt: "2026-05-12T09:05:00Z",
      },
      {
        id: "EDD-007-3",
        label: "Audited Financial Statements",
        required: true,
        description: "Provide the most recent audited financial statements.",
        uploadedFile: {
          id: "DOC-EDD-007-3",
          name: "NorthernStar_2025_Audited.pdf",
          type: "edd_response",
          uploadedAt: "2026-05-12T09:10:00Z",
          url: "#",
        },
        submittedAt: "2026-05-12T09:10:00Z",
      },
    ],
  },
  {
    id: "APP-008",
    status: "edd_required",
    submittedAt: "2026-05-11T08:30:00Z",
    updatedAt: "2026-05-18T10:00:00Z",
    businessInfo: {
      legalName: "Magellan Cross-Border Capital SA",
      dba: "Magellan XB",
      ein: "N/A",
      entityType: "SA",
      stateOfIncorporation: "Luxembourg",
      dateOfIncorporation: "2018-05-22",
      address: {
        street: "20 Avenue Monterey",
        city: "Luxembourg City",
        state: "Luxembourg",
        zip: "L-2163",
        country: "LU",
      },
      phone: "+352-555-0144",
      website: "https://magellanxb.com",
      industry: "Cross-Border Investment",
      description:
        "Luxembourg-domiciled SICAV investing across EU and emerging markets.",
    },
    controlPersons: [
      {
        id: "AP-008",
        firstName: "Sophie",
        lastName: "Beaumont",
        email: "s.beaumont@magellanxb.com",
        title: "Managing Director",
        phone: "+352-555-0145",
        dateOfBirth: "1981-07-08",
        ssn: "N/A",
        address: {
          street: "5 Rue de la Boucherie",
          city: "Luxembourg City",
          state: "Luxembourg",
          zip: "L-1247",
          country: "LU",
        },
        idType: "Passport",
        idNumber: "***5566",
        idExpiration: "2029-07-08",
      },
    ],
    ubos: [
      {
        id: "UBO-010",
        firstName: "Sophie",
        lastName: "Beaumont",
        email: "s.beaumont@magellanxb.com",
        ownershipPercentage: 40,
        dateOfBirth: "1981-07-08",
        ssn: "N/A",
        address: {
          street: "5 Rue de la Boucherie",
          city: "Luxembourg City",
          state: "Luxembourg",
          zip: "L-1247",
          country: "LU",
        },
        idType: "Passport",
        idNumber: "***5566",
        idExpiration: "2029-07-08",
      },
    ],
    documents: [
      {
        id: "DOC-010",
        name: "Statuts SA.pdf",
        type: "formation_document",
        uploadedAt: "2026-05-11T08:25:00Z",
        url: "#",
      },
    ],
    riskScore: 76,
    riskLevel: "high",
    alloyJourneyId: "JRN-MX-001",
    alloyTags: ["eu_entity", "cross_border", "edd_required"],
    eddRequired: true,
    eddDocuments: [
      {
        id: "EDD-008-1",
        label: "AML Program Information",
        required: true,
        description:
          "Provide a copy of the entity's AML program and CSSF compliance attestations.",
      },
      {
        id: "EDD-008-2",
        label: "≥10% UBO Identification",
        required: true,
        description:
          "Identification documentation for all UBOs owning 10% or more.",
      },
      {
        id: "EDD-008-3",
        label: "Enhanced Adverse Media Review",
        required: true,
        description:
          "System-generated adverse media note flagged during initial screen — please provide rebuttal or context.",
        textResponse:
          "[System-generated] Two adverse media hits identified during initial screening. Detail pending client response.",
      },
    ],
  },
];

export const mockAccounts: Account[] = [
  {
    id: "ACCT-001",
    organizationName: "Pinnacle Wealth Advisors Inc",
    applicationId: "APP-003",
    balance: 2450000.0,
    transactionsEnabled: true,
    users: [
      {
        id: "USR-001",
        name: "Diana Park",
        email: "d.park@pinnaclewealth.com",
        role: "Admin",
      },
      {
        id: "USR-002",
        name: "Kevin Nguyen",
        email: "k.nguyen@pinnaclewealth.com",
        role: "Finance Manager",
      },
    ],
    bankAccounts: [
      {
        id: "BA-001",
        bankName: "First Republic Bank",
        accountType: "Checking",
        routingNumber: "****6789",
        accountNumber: "****4321",
        verificationStatus: "verified",
        verificationMethod: "plaid",
        verifiedAt: "2026-04-29T10:00:00Z",
        linkedAt: "2026-04-29T09:45:00Z",
      },
      {
        id: "BA-002",
        bankName: "Silicon Valley Bank",
        accountType: "Savings",
        routingNumber: "****1234",
        accountNumber: "****8765",
        verificationStatus: "pending",
        verificationMethod: "micro_deposit",
        linkedAt: "2026-05-10T14:00:00Z",
      },
    ],
    transactions: [
      {
        id: "TXN-001",
        guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        amount: 1000000,
        rail: "wire",
        direction: "incoming",
        status: "settled",
        dateStarted: "2026-04-30T09:00:00Z",
        dateSettled: "2026-04-30T15:00:00Z",
        to: "Pinnacle Wealth - Interro Account",
        from: "Pinnacle Wealth - First Republic",
      },
      {
        id: "TXN-002",
        guid: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        amount: 1500000,
        rail: "wire",
        direction: "incoming",
        status: "settled",
        dateStarted: "2026-05-05T10:00:00Z",
        dateSettled: "2026-05-05T16:30:00Z",
        to: "Pinnacle Wealth - Interro Account",
        from: "Pinnacle Wealth - First Republic",
      },
      {
        id: "TXN-003",
        guid: "c3d4e5f6-a7b8-9012-cdef-123456789012",
        amount: 50000,
        rail: "ach",
        direction: "outgoing",
        status: "settled",
        dateStarted: "2026-05-10T08:00:00Z",
        dateSettled: "2026-05-12T12:00:00Z",
        to: "Investor - John Smith",
        from: "Pinnacle Wealth - Interro Account",
      },
      {
        id: "TXN-004",
        guid: "d4e5f6a7-b8c9-0123-defa-234567890123",
        amount: 250000,
        rail: "wire",
        direction: "outgoing",
        status: "processing",
        dateStarted: "2026-05-18T14:00:00Z",
        to: "Investor - Emily Johnson",
        from: "Pinnacle Wealth - Interro Account",
      },
      {
        id: "TXN-005",
        guid: "e5f6a7b8-c9d0-1234-efab-345678901234",
        amount: 75000,
        rail: "ach",
        direction: "incoming",
        status: "pending",
        dateStarted: "2026-05-19T09:00:00Z",
        to: "Pinnacle Wealth - Interro Account",
        from: "LP - Horizon Fund",
      },
    ],
    auditLog: [
      {
        id: "AUD-001",
        timestamp: "2026-04-28T16:00:00Z",
        user: "System",
        action: "Account Created",
        details: "Account created upon application approval.",
      },
      {
        id: "AUD-002",
        timestamp: "2026-04-29T09:45:00Z",
        user: "Diana Park",
        action: "Bank Account Linked",
        details:
          "First Republic Bank checking account linked via Plaid.",
      },
      {
        id: "AUD-003",
        timestamp: "2026-05-10T14:00:00Z",
        user: "Kevin Nguyen",
        action: "Bank Account Linked",
        details:
          "Silicon Valley Bank savings account linked via micro-deposit.",
      },
      {
        id: "AUD-004",
        timestamp: "2026-05-15T11:00:00Z",
        user: "Diana Park",
        action: "Business Address Updated",
        details:
          'Address changed from "100 Market St" to "1 Market Street, Suite 3600".',
      },
    ],
  },
];

export const mockRefreshSchedules: RefreshSchedule[] = [
  {
    id: "RS-001",
    applicationId: "APP-003",
    organizationName: "Pinnacle Wealth Advisors Inc",
    riskLevel: "low",
    cadenceMonths: 36,
    responseWindowDays: 90,
    lastRefreshDate: "2026-04-28",
    nextRefreshDate: "2029-04-28",
    status: "current",
  },
  {
    id: "RS-002",
    applicationId: "APP-001",
    organizationName: "Evergreen Capital Partners LLC",
    riskLevel: "low",
    cadenceMonths: 36,
    responseWindowDays: 90,
    lastRefreshDate: "2026-05-15",
    nextRefreshDate: "2029-05-15",
    status: "current",
  },
  {
    id: "RS-003",
    applicationId: "APP-002",
    organizationName: "Meridian Global Ventures Ltd",
    riskLevel: "high",
    cadenceMonths: 12,
    responseWindowDays: 60,
    lastRefreshDate: "2026-05-10",
    nextRefreshDate: "2027-05-10",
    status: "current",
  },
];

export const mockIDExpirations: IDExpiration[] = [
  {
    id: "IDE-001",
    personName: "Diana Park",
    personType: "control_person",
    applicationId: "APP-003",
    organizationName: "Pinnacle Wealth Advisors Inc",
    idExpiration: "2026-06-18",
    status: "expiring_soon",
    notificationSentAt: "2026-05-19T08:00:00Z",
    responseDeadline: "2026-08-17",
  },
  {
    id: "IDE-002",
    personName: "James Mitchell",
    personType: "ubo",
    applicationId: "APP-001",
    organizationName: "Evergreen Capital Partners LLC",
    idExpiration: "2027-08-22",
    status: "valid",
  },
  {
    id: "IDE-003",
    personName: "Ricardo Alvarez",
    personType: "control_person",
    applicationId: "APP-002",
    organizationName: "Meridian Global Ventures Ltd",
    idExpiration: "2027-01-30",
    status: "valid",
  },
];

export function getRiskCadence(riskLevel: string): {
  cadenceMonths: number;
  responseWindowDays: number;
} {
  switch (riskLevel) {
    case "high":
      return { cadenceMonths: 12, responseWindowDays: 60 };
    case "medium":
      return { cadenceMonths: 24, responseWindowDays: 90 };
    case "low":
    default:
      return { cadenceMonths: 36, responseWindowDays: 90 };
  }
}
